version: 1.0.{build}
os:
- Visual Studio 2015
init:
  - git config --global core.autocrlf true
clone_depth: 1
test: off
environment:
  matrix:
  - solution_name: QiTwitterDemo.sln
configuration:
  - Debug
  - Release
platform:
  - Any CPU
build_script:
  - build.cmd --quiet verify
notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/2f6212bd39d4d1641142
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

# http://www.paraesthesia.com/archive/2015/01/12/aspnet-vnext-build-braindump/
