version: 1.0.{build}
os:
- Visual Studio 2015
environment:
  matrix:
  - solution_name: QiTwitterDemo.sln
configuration:
  - Debug
  - Release
platform:
  - Any CPU
nuget:
  account_feed: true
  project_feed: true
before_build:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.2.0-rc/nuget.exe
  - appveyor DownloadFile https://raw.githubusercontent.com/appveyor/ci/master/scripts/nuget-restore.cmd
  - nuget-restore
build_script:
  - msbuild %solution_name%
cache:
  - packages -> **\packages.config